//
// THIS FILE IS AUTOMATICALLY GENERATED! DO NOT EDIT BY HAND!
//

// 编码字符串为 Base64
function encodeBase64(str) {
    const bytes = new TextEncoder().encode(str); // UTF-8 编码
    const binary = Array.from(bytes).map(b => String.fromCharCode(b)).join('');
    return btoa(binary);
  }
  

console.clear()
// 如果配置了下载目录
if (settings.workDir) {

    // hlsUrl 是 m3u8地址

    // 标题
    let title = document.head.querySelector('[property="og:title"]').content;
    // 协议名
    let ProtocolName = 'm3u8dl';
    // 下载参数
    let M3U8dlProtocolParam = `${hlsUrl} --saveName "${title}" --workDir "${settings.workDir}" --enableDelAfterDone --disableDateInfo`;
    // 参数转 Base64
    let b64Param = encodeBase64(M3U8dlProtocolParam);

    // 生成下载按钮
    let _downloadLinkTag = `<a href='${ProtocolName}://${b64Param}'> [ 下载 ] </a>`;
    let titleconteinar = document.getElementsByClassName('header-left')[0];
    titleconteinar.getElementsByTagName('h4')[0].innerHTML = title + _downloadLinkTag
}